version: 0.0
os: linux

files:
- source: /
  destination: /home/ubuntu/server

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 20
      runas: ubuntu
  ApplicationStart:
    - location: start_server.sh
      timeout: 20
      runas: ubuntu
