# Used materials from https://habr.com/ru/company/otus/blog/542144/
version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: yourstrongpasswordhere
      discovery.type: single-node
    networks:
      - elk_stack

  logstash:
    build:
      context: logstash/
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk_stack
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.1
    command: filebeat -e -strict.perms=false
    user: root
    networks:
      - elk_stack
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/usr/share/filebeat/logs
    depends_on:
      - logstash

networks:
  elk_stack:
    driver: bridge

volumes:
  elasticsearch:
 